[package]
name = "raw-uefi"
description = """
UEFI Specification Definitions written in pure Rust.
"""
version = "0.1.0"
edition = "2021"
authors = ["HTGAzureX1212."]
license = "GPL-3.0-only"
repository = "https://github.com/HTG-YT/raw-uefi"

[dependencies]
